server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka  
      
spring:
  cloud:
    gateway:
      default-filters:
      - RewritePath=/polizaJPA/(?<segment>.*), /poliza/${segment}
      - RewritePath=/polizaMybatis/(?<segment>.*), /poliza/${segment}
      routes:
      - id: polizaJPA
        uri: lb://MICROBACKPOLIZASJPA
        predicates:
        - Path=/polizaJPA/**
      - id: polizaMybatis
        uri: lb://MICROBACKPOLIZASMYBATIS
        predicates:
        - Path=/polizaMybatis/**
      - id: polizaFront
        uri: http://localhost:4200/
        predicates:
        - Path=/**
        
        
        
        